name: "Seafile Server"
description: "Seafile Server"
version: "12.0.9-5"
slug: "seafile"
init: false
arch:
  - armv7
  - aarch64
options:
  PORT: 8200
  db_host: "core-mariadb"
  db_port: 3306
  db_user: "seafile"
  db_password: "seafile"
  db_name: "seafile"
  admin_email: "me@example.com"
  admin_password: "secret"
  server_hostname: "homeassistant.local"
  server_protocol: "http"
  server_path: "/"
  enable_seadoc: true
schema:
  PORT: "int"
  db_host: "str"
  db_port: "int"
  db_user: "str"
  db_password: "str"
  db_name: "str"
  admin_email: "str"
  admin_password: "str"
  server_hostname: "str"
  server_protocol: "str"
  server_path: "str"
  enable_seadoc: "bool"
ports:
  "80/tcp": 8200
webui: "http://[HOST]:[PORT:8200]"
