name: "Seafile Server"
description: "Seafile Server"
version: "12.0.9-arm"
slug: "seafile"
init: false
image: "seafileltd/seafile-mc"
arch:
  - armhf
  - armv7
options:
  PORT: 8200
  DB_HOST: "core-mariadb"
  DB_USER: "seafile"
  DB_PASSWORD: "seafile"
  SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: "seafile"
schema:
  PORT: "int"
  DB_HOST: "str"
  DB_USER: "str"
  DB_PASSWORD: "str"
  SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: "str"
#  TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
#  INIT_SEAFILE_ADMIN_EMAIL=${INIT_SEAFILE_ADMIN_EMAIL:-me@example.com}
#  INIT_SEAFILE_ADMIN_PASSWORD=${INIT_SEAFILE_ADMIN_PASSWORD:-asecret}
#  SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
#  SEAFILE_SERVER_PROTOCOL=${SEAFILE_SERVER_PROTOCOL:-http}
#  SITE_ROOT=${SITE_ROOT:-/}
#  NON_ROOT=${NON_ROOT:-false}
#  JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
#  SEAFILE_LOG_TO_STDOUT=${SEAFILE_LOG_TO_STDOUT:-false}
#  ENABLE_SEADOC=${ENABLE_SEADOC:-true}
#  SEADOC_SERVER_URL=${SEAFILE_SERVER_PROTOCOL:-http}://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}/sdoc-server
ports:
  "80/tcp": 8200
webui: "http://[HOST]:[PORT:8200]"
