name: "Seafile Server"
description: "Seafile Server"
version: "12.0.9-arm"
slug: "seafile"
init: false
image: "seafileltd/seafile-mc"
arch:
  - armhf
  - armv7
options:
  PORT: 8200
ports:
  "80/tcp": 8200
webui: "http://[HOST]:[PORT:8200]"
