name: "Seafile Server"
description: "Seafile Server"
version: "12.0.11-0"
slug: "seafile"
init: false
arch:
  - armv7
  - aarch64
  - amd64
options:
  db_host: "core-mariadb"
  db_port: 3306
  db_user: "seafile"
  db_password: "seafile"
  db_seafile_name: "seafile_seafile"
  db_ccnet_name: "seafile_ccnet"
  db_seahub_name: "seafile_seahub"
  admin_email: "me@example.com"
  admin_password: "secret"
  jwt_private_key: "secretkey"
  server_hostname: "homeassistant.local"
  server_protocol: "http"
  server_path: "/"
  storage_path: "/media/data"
schema:
  db_host: "str"
  db_port: "int"
  db_user: "str"
  db_password: "str"
  db_seafile_name: "str"
  db_ccnet_name: "str"
  db_seahub_name: "str"
  admin_email: "str"
  admin_password: "str"
  jwt_private_key: "str"
  server_hostname: "str"
  server_protocol: "str"
  server_path: "str"
  storage_path: "str"
ports:
  "80/tcp": 8200
  "8080/tcp": 8080
webui: "http://[HOST]:[PORT:8200]"
map:
  - "share:rw"
  - "media:rw"
