name: "Collabora CODE"
description: "Collabora CODE"
version: "24.04.5.1.1-1"
slug: "collabora"
init: false
arch:
  - armv7
  - aarch64
  - amd64
options:
  admin_username: "admin"
  admin_password: "homeassistant"
  server_hostname: "homeassistant.local"
  dictionaries: "de_DE en_GB en_US es_ES ffr_FR it nl pt_BR pt_PT ru"
  extra_params: "--o:ssl.enable=false"
schema:
  admin_username: str
  admin_password: str
  server_hostname: str
  dictionaries: str
  extra_params: str
ports:
  "9980/tcp": 9980
webui: "http://[HOST]:[PORT:9980]"
