name: "Restic"
description: "Restic Backup"
version: "0.18.0-5"
slug: "restic"
init: false
startup: "once"
boot: "manual"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  backup_directories:
    - "/media"
    - "/backup"
schema:
  database_user: str
  database_password: str
  database_names:
    - str
  backup_directories:
    - str
  backup_password: str
  backup_target: str
map:
  - "share:ro"
  - "media:ro"
  - "backup:ro"
